### ISSUE TITLE
The Search APIでは全てのTweetを収集することができない

### ISSUE THREAD

**Issue by withforesight000** [withforesight000/twtrtimeseries#2]
@38ta 
https://dev.twitter.com/rest/public/search

> Before getting involved, it’s important to know that the Search API is focused on relevance and not completeness. This means that some Tweets and users may be missing from search results. If you want to match for completeness you should consider using a Streaming API instead.

とあります。なので、Streaming APIということになりますが、
恐らくこれはスクリプトを起動している間のみの全Tweetを取得する流れになるかと思われます。
cf. http://qiita.com/mima_ita/items/ecdf7de2fe619378beee
**（ただしまだ公式サイトでは未確認。）**
こんな仕様でも大丈夫ですか？

**Comment by withforesight000** [comment]
クローズしようと思ったのですが、
https://dev.twitter.com/rest/public/search
> Also note that the search results at twitter.com may return historical results while the Search API usually only serves tweets from the past week.
the past weekってここ1周間って意味ですけどこれは流石に・・・

**Comment by 38ta** [comment]
そう。だから、Search APIは走らせると、基本的にずっとつけっぱなしじゃないと意味ない

**Comment by withforesight000** [comment]
どうします？
それでもsearch apiで実装していく流れでもいいですか？

**Comment by 38ta** [comment]
いや、APIは使わなくていいなら使わない方針でおなしゃす

**Comment by 38ta** [comment]
基本、高度検索結果後に表示されたtwitter上のwebページから、日ごとでツイート数を自動取得することが目標

**Comment by withforesight000** [comment]
スクレイピングっていう手法があることはあるんですけど、難易度高いですw

**Comment by 38ta** [comment]
難関なら今やらなくても、まずは簡単なものからやっていきましょうよ。
手始めに、期間は１日間にして、ヒット件数と合致するか、とか

**Comment by withforesight000** [comment]
https://twitter.com/tos?lang=ja

>ただし、Twitterの事前の承諾なしに本サービスのスクレイピングを行うことは明示的に禁じられています)。

真面目な研究なんで、これも難しいですね…

**Comment by 38ta** [comment]
必要なら、twitterに承認を求めればいいさ

**Comment by withforesight000** [comment]
お願いできます？

**Comment by 38ta** [comment]
もちろん

**Comment by withforesight000** [comment]
1日もしくは1週間のものもひとまず作ってみます

**Comment by withforesight000** [comment]
何度もすいません。

https://blog.twitter.com/2015/full-archive-search-api

> The Full-Archive Search API will now allow Gnip customers to immediately search for any historical public Tweet — ever.

> Customer-focused solutions like the Full-Archive Search API and the new enhanced data enrichments it affords are just the first of new Twitter data products and functionality in the months to come. For more technical information about the Full Archive Search API, you can read our support documentation, and contact the Twitter Data Sales team at data-sales@twitter.com to learn how your business can start using this new historical API today.

ちょっと調べてみます。

**Comment by withforesight000** [comment]
一段落ついたと思われるのでクローズします
